[[install]]
== Git-free install using Powershell script

[source,powershell]
----
Invoke-Expression ((New-Object net.webclient).DownloadString('https://raw.githubusercontent.com/JonasPammer/JonasPammer/master/provisioner-windows/bootstrap.ps1'))
----

This will:

* Install https://chocolatey.org/[chocolatey],
* Install https://git-scm.com/[git] using chocolatey,
* `git checkout` this repository to `$USERPROFILE\Documents\Programmieren\JonasPammer\JonasPammer`, and
* `cd` to this folder


[[config]]
== Configuration

* `config.yml` (git ignored) is read at beginning of each PowerShell Script, or initially created by copying from `config.example.yml` if not existent
* `applications.yml` is used by "Install and Update Applications" Step.


[[pc-setup]]
== Script: PC Setup

[WARNING]
May restart the computer (if `allow_reboot: true`).

[source,powershell]
----
Set-ExecutionPolicy Bypass -Scope Process -Force
./pc-setup.ps1
----

This script aims to be fully automated and not ask anything.
It will:

. Update Windows
. Install 1PasswordCLI (`op`) - to be used in other Script(s).
. Reboot if Windows indicates it is necessary.
.. If not allowed by config [i.e. `allow_reboot: false`], it will stop here [if `exit_anyways_if_reboot_required: true`].
. Install and Update all Applications loaded from `applications.yml` [if `applications_update: true`]
. Setup Powershell Profile (PoshGit, PoshSshell, StartSshAgent)
. Configure Git (gpg-agent, user name/email, and a bunch of settings i once saw recommended)
. Update Antivirus signatures and run a Scan (Windows Defender)
. Install https://learn.microsoft.com/de-de/windows/wsl/[Windows Subsystem for Linux] [if `wsl_install: true`]
. Do a few Windows Registry etc. Tweaks


[[pc-setup-other]]
=== Second, Semi-Automatic part

Pre-requireset: Turn on the  https://developer.1password.com/docs/cli/get-started/#sign-in[1Password desktop app  integration]

. Open and unlock the 1Password app.
. Click your account or collection at the top of the sidebar.
. Turn on Windows Hello in the app.
. Navigate to Settings > Developer.
. Check "Integrate with 1Password CLI".

[source,powershell]
----
Set-ExecutionPolicy Bypass -Scope Process -Force
./pc-setup-other.ps1
----

This will:

. Ask to signin to 1Password
. Download GPG Key from 1Password, Import it, (necessarily) ask the user to enter its trust-level, and configure it as git's `user.signingKey` [`setup_gpg: true`]

== Script: PC Repair

Fixes potential windows problems (automatic)

[source,powershell]
----
 ./pc-repair.ps1
----

[NOTE]
Restarting the computer afterwards is recommended and necessary for it do fully do its job.


[[pc-setup-post]]
== Manual Post-Setup Steps

=== Sign-in

First 2 are Crucial for convenience:

. Firefox
. 1Password Extension

Others:

* 1Password App
* Docker Desktop
* VSCode (easiest choosing GitHub)
* Discord (easiest using Phone with QR Code)
* Steam

=== Enter License Keys

Stored in 1Password.

* Acronis
* Duplicate Cleaner Pro

=== Setup OneDrive

Ensure to uncheck every box (Desktop, Documents, Music..) when asked to setup Backup.

Ensure Folder is `O:\OneDrive` (Letter of Drive may have changed!).

Click on OneDrive's tray Icon, go to (Gear Icon) -> Settings, "Sync and backup" tab, open "Advanced settings" and click "Download all files" under "Files On-Demand".

=== Fix PrntScr

Click on OneDrive's tray Icon, go to (Gear Icon) -> Settings, "Sync and backup" tab, and turn off "Save Screenshots I capture to OneDrive".

Then, ensure in current Screenshot Application of Choice works as expected. As of writing this is:

* Click on ShareX's tray Icon -> "Hotkey Settings"
* Capture Region: Change to "Print Screen" (just the key itself)
* Capture entire screen: "Ctrl + Print Screen"

image::https://github.com/JonasPammer/JonasPammer/assets/32995541/78236737-c416-4c9e-aa44-e80ffa5d61ad[]

=== Setup MEGA.nz Backup of Acronis Backup Storage

TBW

=== Setup MEGA.nz Syncs as required

...

=== Setup Acronis Job

TBW

=== Disable Acronis Hogging the System

TBW

=== _Pin Taskbar Items_



== Attributions:

https://github.com/AgenttiX/windows-scripts (Powershell Goodies)::
MIT License (c) 2020-2023 Mika Mäki

https://gist.github.com/dougwaldron/d510f2d67a922da169aca1aeff7e4c4d (Winget)::
This got me started on my private pc-setup script back in 2022-03-02
