= Applications I use
:toc:
:toc-placement!:

[NOTE]
I now manage my applications in machine-readable format over at
`link:provisioner-windows/applications.yml[applications.yml]`,
which is as part of my `link:provisioner-windows/pc-setup.ps1[pc-setup.ps1]`.
In the future this document will be generated from the above mentioned file when I figured out how I want to do it.
For now this document contains only stuff not fitting for the current yaml file's usage.

// Applications I use very often are in bold. +
// Applications I almost never really use are at the end of tables and in italic. +
// Applications I no longer use are striked through.

toc::[]

== Useful Sites / Bookmarks

Work::
https://www.spelltool.com/de/[spelltool] +
https://www.cbtnuggets.com/certification-playlist[CBTNuggets] +
https://fahrplan.vmobil.at/[VVV Routenplaner]

Dev::
https://devdocs.io/[DevDocs Universal API Documentation] +
https://excalidraw.com/[Excalidraw] +
https://pandoc.org/try/?text=&from=markdown&to=asciidoctor&standalone=0[Pandoc Online] +
https://alldocs.app/convert-mediawiki-markup-to-asciidoc[Pandoc Online, but better] +
https://td4a.codethenetwork.com/[Ansible Template Designer] +
https://docs.ansible.com/ansible-core/2.11/collections/ansible/builtin/index.html#plugins-in-ansible-builtin[Ansible.Builtin — Ansible Core Documentation] +
https://docs.ansible.com/ansible/latest/collections/ansible/utils/[Ansible.Utils — Ansible Documentation] +
https://docs.ansible.com/ansible/latest/collections/community/general/index.html[Community.General — Ansible Documentation] +
https://www.twitch.tv/anthonywritescode[anthonywritescode]

Learn::
https://tryhackme.com/[TryHackMe] +
https://docs.microsoft.com/en-us/learn/[Microsoft Learn] +
http://www.catb.org/~esr/writings/taoup/html/ch01s06.html[Basics of the Unix Philosophy]

Misc::
https://www.lofiatc.com/?icao=koak[lofi air traffic control] +
https://www.supercook.com/#/desktop[SuperCook - Zero Waste Recipe Generator] +
https://pixlr.com/de/x/#editor[Photo Editor : Pixlr X] +
https://vscodecandothat.com/[VS Code Can Do That?] +
https://github.com/iluwatar/java-design-patterns[GitHub - java-design-patterns] +
https://www.exploit-db.com/[exploit-db]

link:about:profiles[Firefox Profiles]

== Firefox Extensions

[cols="a,a"]
|===
| Extension | Description
| https://addons.mozilla.org/en-US/firefox/addon/1password-x-password-manager/[*1Password*]
| Extension for my Password Manager of choice as per 2022
(may switch to self-hosted one in 2024+)

| https://addons.mozilla.org/en-US/firefox/addon/wappalyzer[*Wappalyzer* - Technology profiler]
| Wappalyzer is a browser extension that uncovers the technologies used on websites.
It detects content management systems, eCommerce platforms, web servers,
JavaScript frameworks, analytics tools and many more.
*The most cool extension.*

| https://addons.mozilla.org/en-US/firefox/addon/tabliss[*Tabliss*]
| A beautiful New Tab page with many customisable backgrounds and widgets.

| https://addons.mozilla.org/en-US/firefox/addon/ublock-origin[*uBlock Origin*]
| Finally, an efficient blocker that consumes little processor power and memory.

| https://addons.mozilla.org/en-US/firefox/addon/wayback-machine_new[*Wayback Machine*]
| The Official Wayback Machine Extension - by the Internet Archive.

| https://addons.mozilla.org/en-US/firefox/addon/web-developer[Web Developer]
| Adds a toolbar button with various web developer tools.

| https://addons.mozilla.org/en-US/firefox/addon/keepa[Keepa - Amazon Price Tracker]
| Adds price history charts and the option to be alerted on price drops to all Amazon sites

| https://addons.mozilla.org/en-US/firefox/addon/refined-github[Refined GitHub]
| Simplifies the GitHub interface and adds useful features

| https://addons.mozilla.org/en-US/firefox/addon/darkreader[*Dark Reader*]
| Dark design for any website

| https://addons.mozilla.org/en-US/firefox/addon/compat-report[Combat Report]
| Extends the Developer Tools with a new panel that provides a basic overview
of potential browser compatibility issues, using data from MDN

| https://addons.mozilla.org/en-US/firefox/addon/disable-javascript[*Disable Javascript*]
| Adds the ability to disable JavaScript on specific sites

| https://addons.mozilla.org/en-US/firefox/addon/colorzilla[ColorZilla]
| Color Picker

| https://addons.mozilla.org/en-US/firefox/addon/react-devtools[React Developer Tools]
| Extends the Developer Tools with a useful _React Devtools_ and _React Components_ tab

| https://addons.mozilla.org/en-US/firefox/addon/redux-devtools[Redux DevTools]
| Redux Developer Tools for debugging application state changes.

| https://addons.mozilla.org/en-US/firefox/addon/tab-image-saver[_Tab Image Saver_]
| Save images from all open tabs.

| https://addons.mozilla.org/en-US/firefox/addon/minimaltwitter[Minimal Theme for Twitter]
| Declutters the Twitter web experience

| https://addons.mozilla.org/en-US/firefox/addon/flagfox[Flagfox]
| Niche little extension to show the country of the current urls' web server
right in the address bar

| https://addons.mozilla.org/en-US/firefox/addon/print-edit-we[_Print Edit WE_]
| Adds ability to WYSIWYG edit web pages prior to printing
(Delete, hide and format elements / Edit text / Remove adverts and sidebars / ..)

| https://addons.mozilla.org/en-US/firefox/addon/image-search-options[_Image Search Options_]
| Extends the right click context option menu with diverse array of Image Search Tools
|===

== Linux

[cols="a,a"]
|===
| https://remmina.org[Remmina]
| *RDP*, *VNC*, NX, XDMCP, *SPICE* and *SSH*-Client for POSIX Systems.

https://stackshare.io/JonasPammer/decisions/108493381948748350[
image:https://img.shields.io/badge/View_Decision_on-stackshare-blue?logo=stackshare&logoColor=white[View Decision on StackShare]]
(links to same as PuTTY)

| https://github.com/phw/peek[Peek]
|
Peek makes it easy to create short screencasts of a screen area.
It was built for the specific use case of recording screen areas, e.g. for
easily showing UI features of your own apps or for showing a bug in bug reports.
With Peek, you simply place the Peek window over the area you
want to record and press "Record". Peek is optimized for generating
animated GIFs, but you can also directly record to WebM or MP4 if you prefer.
|===
