:toc:
:toc-placement!:
= 👋 Hey there. My name's Jonas

== About Me

I know my way around Linux, IT and Programming.

I like to get behind the concept of things (*Software is not magic.*) 
and understand what they're _actually_ for before discussing anything or using them. 
I like my software's to do one thing and do it good.

I place a high value on adherence to conventions, documentation, and structured problem solving.

Favourite Series::
Star Trek

Hobbies and Interests::
Programming, Linux, Sports, Learning things, Planning things, Cooking, Watching Movies with Friends

Location::
EU, Austria, Vorarlberg (CET +1 hour)

toc::[]
== My Interest in IT

* I don't limit myself to knowing only part of it. +
  I'm interested in programming, Linux, and the whole DevOps automation cycle,
  but I also cherish an good understanding of IT infrastructures and network protocols/network communications.
+
I also could talk for hours about my enthusiasm for Web Development, especially about the concepts of the Browser and its accompanying protocols/specifications and the prospects they still offer and continue to enable us today.
__Strong Men may look into the source code of this README document to find some words of mine on this.__
// At the end of the day the browser is like a JRE, and HTML/CSS/JS/HTTP/... are the Specifications for it's JVM -
// just with the fact that a "program" (website) "runs it's code" as a second class citizen,
// and the primary "application code" is just structued text (HTML) that is being rendered by the some Engine. +
// (You can hang me for this comparison if you want but it's true).

// NOTE: The following sentence is to be kept in sync with my LinkedIn Info
* 🌱 Having just completed an IT apprenticeship, I am currently studying for various networking certifications to solidify, prove and deepen my knowledge.

// NOTE: The following sentence is to be kept in sync with my LinkedIn Info
* 🌱 I'm currently heavily diving into the topics of *IaaC* with Ansible/Terraform/Amazon Web Services and **C**ontinious Automated **I**ntegration/**D**elivery with GitHub Actions and Docker.
+
These are very fascinating topics that are fundamentally changing the way software development and deployment is done.
Servers / VMs are transformed from sacred "don't touch" black box systems into simple disposable and on-demand createable goods.
It is the pinnacle of automation and reproducibility.
+
And the crazy thing is that nothing has fundamentally changed -
It's just that the solutions (Linux, SSH, HTTP, TLS, ..) and concepts (TCP/IP, ..) that were created a long time ago by very smart people are so crazily thought-of princibles
which we're all just slowly sticking together and extending continously. IT is amazing.

=== My knowledge in IT, a Profile Overview

* 👀 A broad overview of the knowledge and experience I acquired over the years can be found on my
https://www.linkedin.com/in/jonas-pammer-2b340a1aa[image:https://img.shields.io/badge/LinkedIn-0077B5?logo=linkedin&logoColor=white[LinkedIn]],
https://stackshare.io/JonasPammer/my-stack[image:https://img.shields.io/badge/stackshare-blue?logo=stackshare&logoColor=white[stackshare]], and
https://tryhackme.com/p/PixelTutorials[image:https://img.shields.io/badge/TryHackMe-004daa?logo=tryhackme&logoColor=white[tryhackme]] profile -
as well of course on my OSS GitHub Projects.
+
I also actively https://github.com/JonasPammer?tab=stars[star repositories I find useful and interesting].
Below is an automatically generated overview of my GitHub profile, showing mostly my recently starred projects.
(which **give a good indication of what I'm currently onto**).:
+
image::/github-metrics.svg[Metrics]
+
.Footnote on GitHub
____
I use GitHub as my primary version control and collaboration platform.

I also sync my projects to a privately hosted GitLab instance.
I do this mainly for archival purposes (GitHub is owned by Microsoft),
but also to just try things out of course.

Do note that I am currently in the process of refactoring every of my projects
and also try to figure out new development schemes
now that I'm fairly confident in the knowledge i posses
____

=== My knowledge in IT, a Carrer Overview


=== My knowledge in IT, a Certification Overview


[discrete]
=== My humble beginnings (for the very very interested)

NOTE: The following document is very lenghty and nostalgic.

link:JOURNEY.adoc[]



== My Private / Work Setup

include::SETUP.adoc[]

== My Applications

link:APPLICATIONS.adoc[]


image:https://komarev.com/ghpvc/?username=JonasPammer&style=flat-square[image:https://hit.yhype.me/github/profile?user_id=32995541[.,title="Do not worry weary traveller - I am but a simple counter that can only track hits, not visitors. I am being proxied through GitHub to keep your identity safe from the nerd above."]

== Pinned Repositories / Recent Contributions
(see below)
