:toc:
:toc-placement!:
= 👋 Hey there. My name's Jonas

https://www.linkedin.com/in/jonas-pammer-2b340a1aa[image:https://img.shields.io/badge/LinkedIn-0077B5?logo=linkedin&logoColor=white[LinkedIn]]
https://stackshare.io/JonasPammer/my-stack[image:https://img.shields.io/badge/stackshare-blue?logo=stackshare&logoColor=white[stackshare]]

I know my way around Linux, Windows, IT, programming and
generally like to always try to understand most of the things I stumble across every day.

In today's IT world there are a lot of patterns and software.
My mantra is to never forget that https://blog.nelhage.com/post/computers-can-be-understood/[*Computers are not magic and Software _can_ be understood*] --
// - This applies to computer systems, computer networks, communication patterns/flows, and everything else as well.
// One may have to dig very deep and jump over promises upon sales talk upon buzzwords to figure out what all the [new] software and things actually
// (mostly just only) do, but the important thing is that it is still of course possible.
_It is still all just sand that we tricked into thinking by arranging it in complex logical patterns through which electricity paths its way in a very fast way._

I like Software that does one thing very awesomely (not necesarrily one thing _only_ - i don't use Arch btw).

I like to place a high value on adherence to
http://www.catb.org/~esr/writings/taoup/html/ch01s06.html[conventions], documentation and structured problem analyzation.
__In other words__, I still live in my own little https://www.stilldrinking.org/programming-sucks[dream world] 🙂.
// because of my lack in experience working on more real projects with more real people in a more real/defined field.

📺 Favourite Series::
Avatar: The Last Airbender, Star Trek (VOY / TNG / PICARD / DISCOVERY)

⛳ Hobbies and Interests::
Cooking, Watching Movies with Friends, Programming / Linux / IT News, Keeping a clean and organized home and setup

🔝 Current Primary Fascinations::
Ansible Automation and CI/CD (because its Awesome), Cooking (I spend too much € on other things ;))

📍 Location::
EU, Austria, Vorarlberg (CET +1 hour)

== My Interest in IT

* I don't limit myself to knowing only part of it. +
  I'm interested in programming, Linux, and the whole world around https://roadmap.sh/backend[Dev] https://roadmap.sh/devops[Ops],
  but I also cherish an good understanding of IT infrastructures and network protocols/network parts and design.
+
I also could talk for hours about my enthusiasm for Web Development, especially about the concepts of the Browser and its accompanying protocols/specifications and the prospects they still offer and continue to enable us today.
// At the end of the day the browser is like a JRE, and HTML/CSS/JS/HTTP/... are the Specifications for it's JVM -
// just with the fact that a "program" (website) "runs it's code" as a second class citizen,
// and the primary "application code" is just structued text (HTML) that is being rendered by the some Engine. +
// (You can hang me for this comparison if you want but it's true).

// NOTE: The following sentence is to be kept in sync with my LinkedIn Info
* 🌱 Having just completed an IT apprenticeship, I am currently studying for various networking certifications (CCNA, MSCA, FSNE 1-4, RHCSA, ...) to solidify my knowledge and help myself making the decision on which path to truly pursue by digging into each of them.

// NOTE: The following sentence is to be kept in sync with my LinkedIn Info
* 🌱 I'm currently heavily diving into the topics of *IaaC* with Ansible/Terraform/Amazon Web Services and **C**ontinious Automated **I**ntegration/**D**elivery with GitHub Actions and Docker.
+
These are very fascinating topics that are fundamentally changing the way software development and deployment is
https://landscape.cncf.io/[done].
Servers / VMs are transformed from sacred "don't touch" black box systems into simple disposable and on-demand createable goods.
It is the pinnacle of automation and reproducibility.
+
And the crazy thing is that nothing has fundamentally changed -
It's just that the solutions (Linux, SSH, HTTP, TLS, ..) and concepts (TCP/IP, ..) that were created a long time ago by very smart people are so crazily thought-of princibles
which we're all just slowly sticking together and extending continously. IT is amazing.

=== My knowledge in IT

* A broad overview of the knowledge and experience I acquired over the years can be found on my
https://www.linkedin.com/in/jonas-pammer-2b340a1aa[image:https://img.shields.io/badge/LinkedIn-0077B5?logo=linkedin&logoColor=white[LinkedIn]] and
https://stackshare.io/JonasPammer/my-stack[image:https://img.shields.io/badge/stackshare-blue?logo=stackshare&logoColor=white[stackshare]] profiles
// https://tryhackme.com/p/PixelTutorials[image:https://img.shields.io/badge/TryHackMe-004daa?logo=tryhackme&logoColor=white[tryhackme]]  -
as well of course on my OSS GitHub Projects.
+
I also actively https://github.com/JonasPammer?tab=stars[star repositories I find useful and interesting].
Below is an automatically generated overview of my GitHub profile, showing mostly my recently starred projects
(which may give somewhat of an indication of what I'm currently onto):
+
image::./github-metrics.svg[Metrics]
// +
// .Footnote on GitHub
// ____
// I use GitHub as my primary version control and collaboration platform.
//
// I also sync my projects to a privately hosted GitLab instance.
// I do this mainly for archival purposes (GitHub is owned by Microsoft),
// but also to just try things out of course.
//
// Do note that I am currently in the process of refactoring every of my projects
// and also try to figure out new development schemes
// now that I'm fairly confident in the knowledge i posses
// ____

// === My knowledge in IT, a more in-depth Stack Overview


[discrete]
=== A bit about my journey

NOTE: The following document is very lenghty and nostalgic.

link:JOURNEY.adoc[]



== My Private / Work Setup

include::SETUP.adoc[]

== My Applications

link:APPLICATIONS.adoc[]


== Demystifying

Some Summarizations on various Topics I wrote to easily link to.
Sources always linked.

* link:demystifying/module_bundlers.adoc[Demystifying JavaScript Module Bundlers]
* link:demystifying/transpilers.adoc[Demystifying JavaScript Transpilers]
* link:demystifying/linters_and_formatters.adoc[Demystifying Linters and Formatters]
* link:demystifying/asciidoctor.adoc[Demystifying Asciidoc / Asciidoctor]
* link:demystifying/gitignore.adoc[Demystifying `.gitignore`]
* link:demystifying/conventional_commits.adoc[Demystifying Conventional Commits]

---
image:https://komarev.com/ghpvc/?username=JonasPammer&style=flat-square[image:https://hit.yhype.me/github/profile?user_id=32995541[.,title="Do not worry weary traveller - I am but a simple counter that can only track hits, not visitors. I am being proxied through GitHub to keep your identity safe from the nerd above."]

== Pinned Repositories / Recent Contributions
(see below)
