= 👋 Hey there. My name's Jonas

I like to get behind the concept of something and understand what it's _actually_ for.

I place a high value on adherence to conventions, documentation, and structured problem solving.

* As for my interest in IT, I don't limit myself to knowing only part of it. +
  I'm interested in programming, Linux, and the whole DevOps automation cycle,
  but I also cherish an good understanding of IT infrastructures and network protocols/network communications.
* 🌱 Having just completed an IT technician apprenticeship, I am currently studying for various networking certifications on the side to solidify my knowledge in this area.
* 🌱 As for my interest in the programming side, I'm currently fascinated by the topics of IaaC with Ansible, GitHub, Terraform, and Amazon S3/EC2.
* 👀 A broad overview of the knowledge and experience I acquired over the years can be found on my
 https://www.linkedin.com/in/jonas-pammer-2b340a1aa[image:https://img.shields.io/badge/LinkedIn-0077B5?logo=linkedin&logoColor=white[LinkedIn]],
 https://stackshare.io/privat/my-stack[image:https://img.shields.io/badge/stackshare-blue?logo=stackshare&logoColor=white[stackshare]], and
 https://tryhackme.com/p/PixelTutorials[image:https://img.shields.io/badge/TryHackMe-004daa?logo=tryhackme&logoColor=white[tryhackme]] profile -
 as well of course on my OSS GitHub Projects.
 __I also actively https://github.com/JonasPammer?tab=stars[star repositories I find useful and interesting].__

image::/github-metrics.svg[Metrics]


==== Footnote on GitHub

I use GitHub as my primary version control and collaboration platform.

I also sync my projects to a privately hosted GitLab instance.
I do this mainly for archival purposes (GitHub is owned by Microsoft),
but also to just try things out of course.

Do note that I am currently in the process of refactoring every of my projects
and also try to figure out new development schemes
now that I'm fairly confident in the knowledge i posses

image:https://komarev.com/ghpvc/?username=JonasPammer&style=flat-square[image:https://hit.yhype.me/github/profile?user_id=32995541[.,title="Do not worry weary traveller - I am but a simple counter that can only track hits, not visitors. I am being proxied through GitHub to keep your identity safe from the nerd above."]
