= 👋 Hey there. My name's Jonas

I like to get behind the concept of something and understand what it's _actually_ for - 
I see myself more of as a Concept guy, hence the plan and dream of mine to get a master in informatics / computer science. +
I like to embrace Documentation and Conventions. 

* 👀 A broad overview of my knowledge and other interests can be found on my 
 https://www.linkedin.com/in/jonas-pammer-2b340a1aa[image:https://img.shields.io/badge/LinkedIn-0077B5?logo=linkedin&logoColor=white[LinkedIn]], 
 https://stackshare.io/privat/my-stack[image:https://img.shields.io/badge/stackshare-blue?logo=stackshare&logoColor=white[stackshare]], and
 https://tryhackme.com/p/PixelTutorials[image:https://img.shields.io/badge/TryHackMe-004daa?logo=tryhackme&logoColor=white[tryhackme]] profile.
 __I also actively https://github.com/JonasPammer?tab=stars[star repositories I find useful and interesting].__
* ❤️ I love Programming, Linux and the whole cycle of DevOps. This also includes an interest for IT Infrastructure.
* 🌱 I am currently learning IaaC with Ansible, GitHub, GitLab and Amazon S3/EC2. 
* 🤝 I use GitHub as my primary version control and collaboration platform. +
  📫 You can reach me under opensource@jonaspammer.at for personal inqueries of open source matters. 

image::/github-metrics.svg[Metrics]

== Foot notes

I also sync my projects to a privately hosted GitLab instance. 
I do this mainly for archival purposes (GitHub is owned by Microsoft), 
but also to just try things out of course.

Do note that I am currently in the process of refactoring every of my projects
and also try to figure out new development schemes 
now that I'm fairly confident in the knowledge i posses

image:https://komarev.com/ghpvc/?username=JonasPammer&style=flat-square[image:https://hit.yhype.me/github/profile?user_id=32995541[.,title="Do not worry weary traveller - I am but a simple counter that can only track hits, not visitors. I am being proxied through GitHub to keep your identity safe from the nerd above."]
